title: Rajat's Blog
email: rajatrs5054@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Javascript enthusiast

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rajatsingla.in" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Rajat's Blog

date: 2017-10-20 15:34:46 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://rajatsingla.in
google_analytics: UA-82100511-1
gems: [jekyll-paginate]
cover: https://www.javascript.com/images/pages/about/img-about.svg
author_image: https://avatars2.githubusercontent.com/u/16984468?s=400&v=4
# Details for the RSS feed generator
author:        Rajat singla
