title: Rajat's Blog
email: rajatrs5054@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Javascript and Python enthusiast

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rajatsingla.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Rajat's Blog

date: 2020-10-20 12:40:19 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://rajatsingla.com
google_analytics: UA-82100511-1
gems: [jekyll-paginate]
cover: http://rosario.io/images/etna.jpg
author_image: https://avatars2.githubusercontent.com/u/16984468?s=400&v=4
# Details for the RSS feed generator
author:        Rajat singla
